---
- name: Copy .bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: /home/vagrant/.bashrc
    mode: '0755'

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: gitconfig
    dest: /home/vagrant/.gitconfig
    mode: '0755'

- name: Copy .tmux.conf
  ansible.builtin.copy:
    src: tmux.conf
    dest: /home/vagrant/.tmux.conf
    mode: '0755'

- name: Copy starship.toml
  ansible.builtin.copy:
    src: starship.toml
    dest: /home/vagrant/.config/starship.toml
    mode: '0755'
