---
- name: Copy .bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: "{{ home_dir }}/.bashrc"
    mode: '0755'

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: gitconfig
    dest: "{{ home_dir }}/.gitconfig"
    mode: '0755'

- name: Copy .tmux.conf
  ansible.builtin.copy:
    src: tmux.conf
    dest: "{{ home_dir }}/.tmux.conf"
    mode: '0755'

- name: Create .config dir
  ansible.builtin.file:
    path: "{{ home_dir }}/.config"
    state: directory
    mode: '0755'

- name: Copy starship.toml
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ home_dir }}/.config/starship.toml"
    mode: '0755'
