---
- name: Copy .bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: /home/vagrant/.bashrc
    mode: '0755'

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: gitconfig
    dest: /home/vagrant/.gitconfig
    mode: '0755'

- name: Copy scripts to /usr/local/bin
  ansible.builtin.copy:
    src: scripts/
    dest: /usr/local/bin
    mode: '0755'
