---
- name: "Install: ca-certificates"
  ansible.builtin.apt:
    name: ca-certificates
    state: present

- name: "Install: curl"
  ansible.builtin.apt:
    name: curl
    state: present

- name: "Install: gnupg"
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: "Install: htop"
  ansible.builtin.apt:
    name: htop
    state: present

- name: "Install: tree"
  ansible.builtin.apt:
    name: tree
    state: present

- name: "Install: locate"
  ansible.builtin.apt:
    name: locate
    state: present

- name: "Install: git"
  ansible.builtin.apt:
    name: git
    state: present

- name: "Install: yamllint"
  ansible.builtin.apt:
    name: yamllint
    state: present

- name: "Install: tmux"
  ansible.builtin.apt:
    name: tmux
    state: present

- name: "Install: tpm for tmux"
  ansible.builtin.shell: |
    git clone https://github.com/tmux-plugins/tpm "{{ home_dir }}/.tmux/plugins/tpm"
  args:
    creates: "{{ home_dir }}/.tmux/plugins/tpm"

- name: "Install: neofetch"
  ansible.builtin.apt:
    name: neofetch
    state: present

- name: "Install: fuse3"
  ansible.builtin.apt:
    name: fuse3
    state: present

- name: "Install: systemd-timesyncd"
  ansible.builtin.apt:
    name: "systemd-timesyncd"
    state: present

- name: "Install: unzip"
  ansible.builtin.apt:
    name: "unzip"
    state: present

#- name: "Install: starship"
#  ansible.builtin.shell: |
#    curl -sS https://starship.rs/install.sh | sh -s -- --yes
#  args:
#    creates: /usr/local/bin/starship

- name: "Install: batcat"
  ansible.builtin.apt:
    name: "bat"
    state: present
