---
- name: "Install: ca-certificates"
  ansible.builtin.apt:
    name: ca-certificates
    state: present

- name: "Install: curl"
  ansible.builtin.apt:
    name: curl
    state: present

- name: "Install: gnupg"
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: "Install: git"
  ansible.builtin.apt:
    name: git
    state: present

- name: "Install: tmux"
  ansible.builtin.apt:
    name: tmux
    state: present

- name: "Install: tpm for tmux"
  ansible.builtin.shell: |
    git clone https://github.com/tmux-plugins/tpm /home/vagrant/.tmux/plugins/tpm
  args:
    creates: /home/vagrant/.tmux/plugins/tpm
