# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"

  config.vagrant.plugins = "vagrant-qemu"
  config.vagrant.plugins = "vagrant-sshfs"
  config.vm.provider :qemu do |qemu|
    qemu.machine = "virt,accel=hvf,highmem=on"
    qemu.cpu = "max"
    qemu.smp = "4"
    qemu.cpu_affinity = "0-3"
    qemu.memory = "4G"
  end

  config.vm.hostname = "debian-workstation"
  
  config.vm.synced_folder "/Users/mark.smith/projects", "/home/vagrant/projects",
    type: "sshfs"

  config.vm.synced_folder ".", "/vagrant", type: "rsync"
 
  # Resize the filesystem after setting machine_virtual_size
  #config.vm.provision "shell", inline: <<-SHELL
  #  growpart /dev/vda 1
  #  resize2fs /dev/vda1
  #SHELL
 
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y    
    apt-get install -y ansible
    ansible-galaxy install -r /vagrant/ansible/roles/requirements.yml
  SHELL

  config.vm.provision "ansible_local" do |ansible|
    ansible.become = true
    ansible.playbook = "ansible/site.yml"
    ansible.inventory_path = "ansible/production.ini"
    ansible.limit = "localhost"
  end

  config.vm.provision "shell", inline: <<-SHELL
    chown -R vagrant:vagrant /home/vagrant
  SHELL
end
