---
- name: "Installing build-essential"
  ansible.builtin.apt:
    name: "build-essential"
    state: present

#- name: Installing golang
#  ansible.builtin.apt:
#    name: golang
#    state: present

#- name: Installing nodejs
#  ansible.builtin.apt:
#    name: nodejs
#    state: present

#- name: Installing npm
#  ansible.builtin.apt:
#    name: npm
#    state: present

- name: Installing python3-venv
  ansible.builtin.apt:
    name: python3-venv
    state: present

- name: Installing python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

#- name: Rust - check if cargo is installed
#  shell: command -v /root/.cargo/bin/cargo
#  register: cargo_exists
#  ignore_errors: true

#- name: Rust - Download Installer
#  when: cargo_exists is failed
#  get_url:
#    url: https://sh.rustup.rs
#    dest: /tmp/sh.rustup.rs
#    mode: '0755'
#    force: 'yes'

#- name: Rust - install rust/cargo
#  when: cargo_exists is failed
#  shell: /tmp/sh.rustup.rs -y

#- name: Copy /root/.cargo to /home/
#  when: cargo_exists is failed
#  ansible.builtin.copy:
#    remote_src: true
#    src: /root/.cargo
#    dest: "{{ home_dir }}"
#    owner: vagrant
#    group: vagrant
