---
- name: "Install: X-Server"
  ansible.builtin.apt:
    name: xorg 
    state: present

- name: "Install: Display Manager"
  ansible.builtin.apt:
    name: gdm3 
    state: absent

- name: "Install: Display Manager"
  ansible.builtin.apt:
    name: lightdm 
    state: present

- name: "Install: Window Manager"
  ansible.builtin.apt:
    name: i3
    state: present

- name: "Install: firefox"
  ansible.builtin.apt:
    name: firefox-esr
    state: present
