# To be appended to .bashrc

export PATH=~/bin:$PATH

# Was recommended to not build on a virutalbox mount (/home/vagrant)
#export CARGO_TARGET_DIR=/tmp/rust

alias python='python3'
# alias vi='/usr/bin/nvim'
alias ls='ls --color=auto'
alias sudo='sudo ' # Use aliases with sudo
alias ctop='TERM="${TERM/#tmux/screen}" ctop'
alias cat='/usr/bin/batcat'

[ -f ~/.cargo/env ] && source $HOME/.cargo/env
eval "$(starship init bash)"
