command_timeout = 2000

[character]
#success_symbol = '\$'

[hostname]
disabled = true
style = 'bold green'
format = '[$hostname]($style):'

[username]
disabled = true
style_user = 'bold green'
format = '[$user@]($style)'

[directory]
#style = 'bold blue'

[aws]
disabled = true
