---
- name: Installing docker-ce
  ansible.builtin.apt:
    name: docker-ce
    update_cache: true
    state: present

- name: Installing docker-ce-cli
  ansible.builtin.apt:
    name: docker-ce-cli
    state: present

- name: Installing containerd.io
  ansible.builtin.apt:
    name: containerd.io
    state: present

- name: Installing docker-buildx-plugin
  ansible.builtin.apt:
    name: docker-buildx-plugin
    state: present

- name: Installing docker-compose-plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
