---
# https://docs.docker.com/engine/install/debian/#install-using-the-repository 

## Prerequisites
- name: "Install: ca-certificates"
  ansible.builtin.apt:
    name: ca-certificates
    state: present

- name: "Install: curl"
  ansible.builtin.apt:
    name: curl
    state: present

- name: "Install: gnupg"
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: "Check if docker key exists"
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_key

- name: "Add keyrings if needed"
  ansible.builtin.shell: install -m 0755 -d /etc/apt/keyrings
  when: not docker_key.stat.exists 

- name: Add docker key to keyring
  ansible.builtin.shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
  when: not docker_key.stat.exists 

- name: chmod docker key
  ansible.builtin.shell: 'chmod a+r /etc/apt/keyrings/docker.gpg'
  when: not docker_key.stat.exists 

- name: "Check if docker package repo exists"
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_repo

- name: Add docker package repo
  ansible.builtin.shell: 'echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'
  when: not docker_repo.stat.exists 
