---
- name: Installing AWS CLI
  ansible.builtin.apt:
    name: awscli
    state: present

- name: "Create {{ home_directory }}/.aws directory"
  file:
    path: "{{ home_directory }}/.aws"
    state: directory
    mode: '0755'

- name: Copy aws config file
  ansible.builtin.copy:
    src: aws_config
    dest: "{{ home_directory }}/.aws/config"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0600'

- name: Copy aws credentials file
  ansible.builtin.copy:
    src: aws_credentials
    dest: "{{ home_directory }}/.aws/credentials"
    force: false
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0600'
