---
- name: Install the Microsoft signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add the azure-cli apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ansible_distribution_release}} main"
    filename: "azure-cli"
    state: present

- name: Test to see if azure-cli is installed
  ansible.builtin.stat:
    path: /usr/bin/az
  register: azure_cli_bin

- name: Install azure-cli
  ansible.builtin.apt:
    name: "azure-cli"
    update_cache: yes
  when: azure_cli_bin.stat.exists != true

- name: Set azure-cli to auto-upgrade
  ansible.builtin.shell: |
    az config set auto-upgrade.enable=yes
  when: azure_cli_bin.stat.exists != true
